version: "3.7"

services:
  weewx-python:
    build: .
    ports:
      - 9877:9877
    volumes:
      - weewx-db:/home/weewx/archive
      - weewx-html:/home/weewx/public_html
    restart: unless-stopped
  weewx-web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - weewx-html:/usr/share/nginx/html

volumes:
  weewx-db:
  weewx-html: